### ISSUE TITLE
圖片插入失敗

### ISSUE THREAD

**Issue by leeuho16** [RPMTW/RPMTW-Wiki#32]
提交前
![image](https://user-images.githubusercontent.com/88672052/152687222-f0aefa6d-8d5f-4273-a37b-61d81fb08e71.png)
提交後
實際顯示
![image](https://user-images.githubusercontent.com/88672052/152687250-a552ea10-7305-4eda-ab21-7aef8acde53d.png)
重新編輯連結消失
![image](https://user-images.githubusercontent.com/88672052/152687311-0f0bb168-72c0-46a1-a4b9-4d3226cc8349.png)

**Comment by leeuho16** [comment]
~~我圖片好像放錯模組w~~

**Comment by SiongSng** [comment]
我這邊看是有正常插入的，可能是瀏覽器快取導致
https://wiki.rpmtw.com/mod/view/b5ad76fe-1437-46b2-81fe-c9b4d639eaad
