### ISSUE TITLE
圖片錯誤

### ISSUE THREAD

**Issue by leeuho16** [RPMTW/RPMTW-Wiki#43]
在未有編輯的狀況下出現圖片錯誤
![image](https://user-images.githubusercontent.com/88672052/160139290-58013e4f-e952-4f89-b654-6969c77822aa.png)
![image](https://user-images.githubusercontent.com/88672052/160139324-2baadcb7-529c-436a-9baf-89db0a356b3a.png)

**Comment by SiongSng** [comment]
我這裡測試正常，麻煩您再測試看看，如果仍然顯示這樣請附上您的作業系統、使用的瀏覽器 感謝配合

![圖片](https://user-images.githubusercontent.com/48402225/160150243-95e61be0-5262-4efd-be86-c6ba8c4f406e.png)

**Comment by leeuho16** [comment]
在多次重新整理網頁即修正,應該是我的問題,抱歉打擾
